In [18]:
import torch

In [19]:
W = torch.tensor([[1., -1.], [1., -1.]])

In [20]:
W

tensor([[ 1., -1.],
        [ 1., -1.]])

In [21]:
W2 = W

In [22]:
W2[0][0] = 10

In [23]:
W

tensor([[10., -1.],
        [ 1., -1.]])

In [24]:
W2

tensor([[10., -1.],
        [ 1., -1.]])

In [25]:
W = torch.tensor([[1., -1.], [1., -1.]])
W2 = W
W2[0][0] = 2 # 更改W2的值
print(W) # 输出：tensor([[2., -1.], [1., -1.]])

tensor([[ 2., -1.],
        [ 1., -1.]])
