In [1]:
import numpy as np
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter
import pickle
import re

from common.util import preprocess, create_co_matrix, create_contexts_target, convert_one_hot

In [2]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

In [3]:
contexts, target = create_contexts_target(corpus, window_size=1)

In [4]:
contexts

tensor([[0, 2],
        [1, 3],
        [2, 4],
        [3, 1],
        [4, 5],
        [1, 6]])

In [5]:
vocab_size = len(word_to_id)
target = convert_one_hot(target, vocab_size)
contexts = convert_one_hot(contexts, vocab_size)

In [6]:
target

tensor([[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.]])

In [7]:
contexts

tensor([[[1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.]],

        [[0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.]],

        [[0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0.]],

        [[0., 0., 0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0.]],

        [[0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1.]]])